FROM python:3.9.9-bullseye

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install \
    --no-cache-dir \
    -r requirements.txt

COPY . .
CMD ["uvicorn", "app:api", "--host", "0.0.0.0", "--port", "8000"]

