FROM python:3.9.9-bullseye

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install \
    --no-cache-dir \
    -r requirements.txt

RUN apt-get update && apt-get upgrade -y \
 && rm -rf /var/lib/apt/lists/*

COPY . .
CMD ["uvicorn", "app:api", "--host", "0.0.0.0", "--port", "8000"]

